### ISSUE TITLE
export analysis-ready data (ARD) for CCiA on NCI

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [Thomas-Moore-Creative/NCI-CCiA-ARD#1]
- [ ] ~~test an export of dictionaries to disk.  Any barriers or problems writing / reading back in?~~
- [x] utilise `intake-esm` catalogs to create `path objects` for the raw CMIP5 output for each of these eight [CCiA models](https://www.climatechangeinaustralia.gov.au/en/learning-support/faqs/eight-climate-models-data/) // NB: this wouldn't be possible without work from [Scott Wales (CLEX)](https://nbviewer.jupyter.org/gist/ScottWales/7402c7c5cbd96f6bed62f810899b611a) & [Francois Delage (BOM)](https://git.nci.org.au/pfd548/bom-climate-change-variability-and-extreme-toolbox)
- [ ] ~~expand and combine `path objects` into dictionary with model & experiment metadata linked to correct file paths.~~
- [x] how do we best deal with inconsistent presence of ensembles? (use `r1i1p1` only)
- [x] how do we deal with lack of `latest` version tag and models with *different* last versions across their ensembles? (don't use `catalog.esgf.cmip5_all`)
- [x] use `xr.open_mfdataset` to automatically deal with different ways of breaking up date ranges.
- [ ] ~~write function to read in an `xarray` dataset based on dictionary and metadata~~
- [ ] ~~start with individual `xarray` datasets for each model AND experiment AND ensemble~~
- [ ] ~~reduce ensembles via `mean`~~
- [ ] ~~export to `zarr`~~
- [x] write a quick gist to bring into other notebooks

**Comment by Thomas-Moore-Creative** [comment]
Shifting away from exporting an all-encompassing dictionary for `xarray` to open datasets against.  For expediency and deadlines moving towards just building up datasets for each model / experiment / ensemble.

```# manually check and enter # of ensembles as they vary across models
CCiA_HadGEM2_CC_rcp85_r1i1p1_catalog = NCI_catalog.esgf.cmip5_all.search\
(institute="MOHC",variable=['psl','pr'],time_frequency='mon',experiment='rcp85',model='HadGEM2-CC',ensemble='r1i1p1')
if CCiA_HadGEM2_CC_rcp85_r1i1p1_catalog.unique('version')['version']['count'] == 1:
    CCiA_HadGEM2_CC_rcp85_r1i1p1_ds = xr.open_mfdataset(CCiA_HadGEM2_CC_rcp85_r1i1p1_catalog.unique('path')['path']['values'])
else:
    print("there's more than one version so write some kind of logic here to deal with it")
CCiA_HadGEM2_CC_rcp85_r1i1p1_ds    ```

**Comment by Thomas-Moore-Creative** [comment]
oh yes, we also have different ways of breaking up both the historical and projection time periods across models.

**Comment by Thomas-Moore-Creative** [comment]
And for `versions`: not every ensemble in an experiment for a model will have the same number of versions or the same date of version?

**Comment by Thomas-Moore-Creative** [comment]
and there can be different versions / number of versions depending on which specific `date_range` you are looking at?  This seems labyrinthine and very hard to generalise.

**Comment by Thomas-Moore-Creative** [comment]
.... AND (OMG) even within a single model's historical run, different ensembles can have *different* date_ranges!?!?  As in (1) same experiment but covering different total date ranges and (2) broken up into filenames that are subtly different. `198412-200512` vs `198412-200511`

I can't see how every model & experiment combination doesn't require it's own boutique approach!?!?!

**Comment by Thomas-Moore-Creative** [comment]
I'm trying to write general code for 2 (variables) X 2 (experiments) X 8 (models) with differing number of ensembles.  In the one case of HadGEM2_CC it appears that just the historical run has 3 ensembles that cover two different total periods and sometimes end on 200511 and sometimes 200512.  The catalogs are a great aid above searching the linux command line but I'm still facing boutique code for all 32 of the cases - all slightly different and all easy to make wrong with a single mistyped number or letter.

**Comment by Thomas-Moore-Creative** [comment]
UPDATE: the lack of `latest` metadata in the `al33` project is diabolical.  Despite the usefulness of an `intake-esm` catalog being unable to filter via `version="latest"` is frustrating.  I note the availability (duplication??) of CMIP5 data on project `r87` and with `latest` metadata in path names.  It appears this isn't in the catalog so possibly bailing on the power of `intake` for hand made path lists from `r87`?

**Comment by Thomas-Moore-Creative** [comment]
UPDATE: The author (me) made an early syntax error that gave the impression that `catalog.esgf.cmip5_all` needed to be used to capture all the CCiA data.  This was wrong.  In fact using `catalog.esgf.cmip5` provides only the latest data. NB: the keys still contain all the versions.

**Comment by hot007** [comment]
> UPDATE: the lack of `latest` metadata in the `al33` project is diabolical. Despite the usefulness of an `intake-esm` catalog being unable to filter via `version="latest"` is frustrating. I note the availability (duplication??) of CMIP5 data on project `r87` and with `latest` metadata in path names. It appears this isn't in the catalog so possibly bailing on the power of `intake` for hand made path lists from `r87`?

Just FYI it's not duplication, it's a symlink tree built from what's in al33/rr3 into a single structure meeting the needs of users who want to find all data together and with a 'latest' path. 
But I am very happy to hear the intake catalogue actually does do the thing you need!!

**Comment by Thomas-Moore-Creative** [comment]
... thanks for following along and the informed commentary @hot007
